-- Create table for users
CREATE TABLE cb_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(100) NOT NULL,
  email_address VARCHAR2(100) NOT NULL,
  office_address VARCHAR2(150),
  nationality VARCHAR2(50),
  phone_number VARCHAR2(20) UNIQUE NOT NULL,
  bank_name VARCHAR2(100),
  bank_account_no VARCHAR2(50),
  pin_code VARCHAR2(10) NOT NULL,
  cbdc_balance NUMBER(20, 2) DEFAULT 0 NOT NULL,
  bank_balance NUMBER(20, 2) DEFAULT 0 NOT NULL
);

-- Create table for transactions (CBDC or bank-related)
CREATE TABLE cb_transactions (
  tx_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  amount NUMBER(20, 2) NOT NULL,
  tx_type VARCHAR2(50) NOT NULL, -- e.g. 'CBDC Transfer', 'Bank Transfer'
  tx_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES cb_users(user_id)
);

-- Optional: Indexes for performance
CREATE INDEX idx_cb_users_phone ON cb_users(phone_number);
CREATE INDEX idx_cb_transactions_user ON cb_transactions(user_id);

-- Optional: Seed data
INSERT INTO cb_users (
  full_name, email_address, office_address, nationality, phone_number,
  bank_name, bank_account_no, pin_code, cbdc_balance, bank_balance
) VALUES (
  'Demo User', 'demo@sadc.org', '100 Finance St, SADC', 'South Africa',
  '+27111222333', 'SADC Reserve Bank', '9876543210', '1234', 50000, 10000
);

COMMIT;




-- Users table
CREATE TABLE cb_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number VARCHAR2(20) UNIQUE NOT NULL,
  pin_code VARCHAR2(10) NOT NULL,
  cbdc_balance NUMBER(20, 2) DEFAULT 1000000000000,
  bank_balance NUMBER(20, 2) DEFAULT 0,
  bank_name VARCHAR2(100),
  bank_account_no VARCHAR2(50)
);

-- Transactions table
CREATE TABLE cb_transactions (
  tx_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  amount NUMBER(20, 2),
  tx_type VARCHAR2(50),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES cb_users(user_id)
);
