
-- Users table
CREATE TABLE cb_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number VARCHAR2(20) UNIQUE NOT NULL,
  pin_code VARCHAR2(10) NOT NULL,
  cbdc_balance NUMBER(20, 2) DEFAULT 1000000000000,
  bank_balance NUMBER(20, 2) DEFAULT 0,
  bank_name VARCHAR2(100),
  bank_account_no VARCHAR2(50)
);

-- Transactions table
CREATE TABLE cb_transactions (
  tx_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER,
  amount NUMBER(20, 2),
  tx_type VARCHAR2(50),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES cb_users(user_id)
);
